### ISSUE TITLE
Feature: Alias

### ISSUE THREAD

**Issue by seerickcode** [DandyDev/slack-machine#107]
I would be interested in having an 'alias' feature so that instead of @botname, just a symbol could be used.

I am looking at porting my plugin from lins05/slackbot and this is a feature I currently use to give a slash command like effect so users don't need to `@botname` every time.

I already coded it up, tested, and working in my fork (alias branch), but figured I would check if this is something you would be open to as a PR before I dive into setting up unit tests.

**Comment by DandyDev** [comment]
Sounds like a good idea. I'd be glad to see a PR for that!

**Comment by seerickcode** [comment]
Closing my feature request as PR has been merged.  Thanks !
