### ISSUE TITLE
Altering RESPOND_MATCHER to match multiline messages.

### ISSUE THREAD

**Issue by smoothimpact** [DandyDev/slack-machine#125]
Just noticed that the RESPOND_MATCHER in dispatch.py doesn't match messages such as:

```
@botname line 1
line 2
```

Adding re.DOTALL to RESPOND_MATCHER looks like it addresses this (and hopefully doesn't cause any other side effects).

**Comment by seerickcode** [comment]
Issue hit me today as well.   No amount of regex changing in the respond_to will work if the text isn't even getting to you.
