### ISSUE TITLE
Need help listing users

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#143]
Hello , i need to list all users of my slack team , how can i do that ?
thx

**Comment by dorel14** [comment]
I've started like this 

`from machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import respond_to


class listusers(MachineBasePlugin):
    @respond_to(r"^liste users")
    def list(self, msg):
        utilisateurs = listusers.users()
        print(utilisateurs)`

and i have this result 
`[2019-03-05 22:18:08][ERROR] machine.utils.pool pool.py:run:24 | An error occurred while performing work
Traceback (most recent call last):
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/utils/pool.py", line 21, in run
    func(*args, **kargs)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/dispatch.py", line 47, in handle_event
    self._dispatch_listeners(listeners, respond_to_msg)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/dispatch.py", line 104, in _dispatch_listeners
    l['function'](message, **match.groupdict())
  File "/home/pi/projets/supportBot/mybot/plugins/users.py", line 8, in list
    utilisateurs = listusers.users()
TypeError: 'property' object is not callable
`

Can someone help me ?

**Comment by seerickcode** [comment]
TypeError: 'property' object is not callable
try instead...
`utilisateurs = listusers.users`

**Comment by dorel14** [comment]
here is the result 

<property object at 0x75e52e70>

**Comment by seerickcode** [comment]
Sorry, missed another issue with your code - you're calling against the class, not the instance of the class.  Not a slack-machine issue, just a python use issue.

Try:
```
   @respond_to(r"^users$")
    def respond_users(self, msg):
        users = self.users
        print(users)
        message = f"{users}"
        msg.say(message)
```

**Comment by DandyDev** [comment]
What @seerickcode says is completely correct

**Comment by dorel14** [comment]
Hi 
Perfect thx 
I'm new to python and discover it day by day
