### ISSUE TITLE
Issue : little pb slack machine repeat himself

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#146]
Hello 
my slack-machine is installed on a raspberry machine in a virtual env 
i have this plugin which is very simple 
`rom machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import listen_to
import re

class aide(MachineBasePlugin):
    @listen_to(r"help?")
    @listen_to(r"aide")
    @listen_to(r"au secours")
    def helpFunc(self, msg):
        msg.reply(
            "Pour l'astreinte indiquer : astreinte : la personne d'astreinte ; date : le lundi de la semaine d'astreinte")
`
when i type help? in slack i have 2 answers 

![image](https://user-images.githubusercontent.com/10910133/52881064-e11fed00-3163-11e9-87c3-e9c6528e3b74.png)

**Comment by seerickcode** [comment]
Perhaps the one of the default plugins machine.plugins.builtin.help.HelpPlugin is running ?

See https://slack-machine.readthedocs.io/en/latest/user/usage.html#configuring-slack-machine and the PLUGINS array. 

Though, I think that plugin would only responds to `help` not `help?`

Are the two answers the same ?  (your msg.reply message above ?)

**Comment by dorel14** [comment]
Yes , the two aswers are the same  and Helplugin is not activated
This pb is the same for all my plugins and only on debian ,  i try same plugins on a windows install and it's ok

**Comment by dorel14** [comment]
hello , today i'v tried to make the help plugin work , fail 
can you give an example of a help text in a plugin 
thx

**Comment by dorel14** [comment]
Hello , the problem is solved 
I've started 2 instances of slack machine (1 on windows and the other one on linux ) 
Your app works perfect
