### ISSUE TITLE
FR : Capture text snippets

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#161]
Hello
i'have tested this code 
`from machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import process

class testevents(MachineBasePlugin):
    @process("file_created")
    def testFileUploadDetection(self, event):
        self.say('ok')`

and nothing happen when added a file to my slack team

**Comment by dorel14** [comment]
Hello
I've made it work  , but i needed to import slack client , which is not optimal
here is the code of my plugins , can you help me doing everythong with slack machine ?

`class testevents(MachineBasePlugin):
    @process("file_shared")
    def testFileUploadDetection(self, event):
        token = self.settings['SLACK_API_TOKEN']
        sc = SlackClient(token)
        snippet_id = event['file_id']
        request = sc.api_call("files.info", file=snippet_id)
        if request['ok']:
            titre = request['file']['title']
            text = request['file']['preview']
            contenu = request['content']
            #commentaire = request['comments']
            self.say('general', titre + ' ' + ' ' +
                     text + ' ' + contenu)`

**Comment by seerickcode** [comment]
You will only ever get the 'preview' from the files.info.  
The full 'preview' contents are actually sent via a 'Message" event that looks like this.
The distinguishing factor is that it will have a files list in the event.

```{
   'type':'message',
   'text':'',
   'files':[
      {
         'id':'FJ4MJEBE1',
         'created':1556079783,
         'timestamp':1556079783,
         'name':'-.pl',
         'title':'Untitled',
         'mimetype':'text/plain',
       ----cut-----
```

So you could have a generic watch on `message` types, query for files inside, and pull the preview from there, but the preview will be just that, a small preview.   If you want the full file, then you will need to get the file, at the url in `url_private_download` field in the event data.

You will need to fetch it with something like requests, and provide the slack api token in the header.

Here is a snip of how I do it

```
            _req = requests.get(
                _file_external_url,
                allow_redirects=True,
                headers={"Authorization": f"Bearer {self.settings['SLACK_API_TOKEN']}"},
            )
            if _req.status_code != 200:
                raise NotFoundError(
                    "Unable to get file from Slack - {_req.status_code}"
                )
           _body = _req.text
```
_body is the actual raw contents of the snippet.    

It could be implemented as a special feature of slack-machine I suppose, but until then, this could be a workable solution for you.

FYI - in my use case, when the user is about to send a snippet for the bot to work on, I just also have them put in the "Add Message" box, a respond_to / listen_to trigger phrase.   That way I don't have to setup special event processing, I just use respond_to / listen_to, and the files collection will be in the message._msg_event['files'] list.

**Comment by dorel14** [comment]
Hi 
Thx for your answer , it helps me a lot
Here is the final code for the moment , i wiil plug it later with a sms alerting system

`class testevents(MachineBasePlugin):
    @listen_to(r"alerte")
    def testAlertmsg(self, msg):
        testFile = msg._msg_event.get('files', None)
        if testFile is not None:
            for f in msg._msg_event['files']:
                if f['mode'] == "snippet":
                    _file_external_url = f['url_private']
                    titre_snip = f['title']
                    token = self.settings['SLACK_API_TOKEN']
                    _req = requests.get(_file_external_url,
                                        allow_redirects=True,
                                        headers={
                                            'Authorization': 'Bearer ' + token}
                                        )
                    if _req.status_code != 200:
                        raise ValueError(
                            "Unable to get file from Slack - " +
                            {_req.status_code}
                        )
                    texte_snip = _req.text
                    print(titre_snip + ' ' + texte_snip)`
