### ISSUE TITLE
Bot can respond to self using {say,reply}_webapi

### ISSUE THREAD

**Issue by preludedrew** [DandyDev/slack-machine#191]
@DandyDev i have a listen_to function that listens for jira ticket mentions via regex in any message, and responds via `say_webapi()`. The problem im facing right now, is using `*_webapi()`, allows the bot to respond to itself, and in the case of `say_webapi()`, it's infinite. I have a quick fix for this, curious what your thoughts are. I'll upload a patch or at least a diff when I can, but in the mean time...
in `handle_event()` I'm wrapping the message events in
```
if not event['user'] == self._get_bot_id():
```

**Comment by DandyDev** [comment]
This has been fixed now.
