### ISSUE TITLE
Help on init()

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#201]
Hello , can you provide me some help how to use it ?
Thx

**Comment by seerickcode** [comment]
It's just a method you add to your plugin class that is called at plugin load time by slack-machine.
Run whatever code you want your plugin to do once, at start.

eg.. I use it sometime to get a database connection for the plugin going.
(hypothetical example)
```
class SomePluginWithDB(MachineBasePlugin):
    def init(self):
        self.db = self.db = DB(self.settings["SOMEPLUG_DBURL"])

    def get_tenant_list(self, msg):
        with self.db.session() as s:
            results = s.query(Tenants).all()
            message.reply(f"Tenants: {results}")
````

**Comment by DandyDev** [comment]
Exactly! To be fair, it it explains [right there in the documentation](https://slack-machine.readthedocs.io/en/latest/api.html#machine.plugins.base.MachineBasePlugin.init)

**Comment by dorel14** [comment]
THx  a lot
