### ISSUE TITLE
self.web_client.channels_list

### ISSUE THREAD

**Issue by smoothimpact** [DandyDev/slack-machine#290]
Hi there,

Great to see the move towards slackclient v2 - thanks for all the work on the new version.

After debugging a KeyError relating to my tests with the new version (in which I was testing in a DM and a private channel) it seems the use of `self.web_client.channels_list` in `machine/clients/singletons/slack.py` may be causing it, due to it not including the same level of conversation coverage as `conversations.list`.  At the moment, this appears to prevent the bot responding to private channel/DM messages.

Regards,
Kris

**Comment by DandyDev** [comment]
Hi @smoothimpact, this was fixed in the latest version. You can upgrade to [v0.20](https://pypi.org/project/slack-machine/0.20.0/) to get this fix.
