### ISSUE TITLE
Bug with bottle

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#292]
Hello 
To make slack machine configurable , i've made a web backoffice  , i"ve updated my developpement environnemnt to your latest version and nothing is working anymore on this backoffice, here an example of my plugin join

`from machine.plugins.base import MachineBasePlugin
import bottle

class html(MachineBasePlugin):
    @bottle.route('/')
    def index():
        heure = datetime.datetime.now().strftime(
            "<p>Nous sommes le %d/%m/%Y, il est %H:%M:%S</p>" )
        return bottle.template('index.tpl', title='Horloge',
                               title2='Bienvenue dans votre Backoffice ',
                               body=heure)`
while everything is ok with old version , with the new one i have  404 not found
i don't use your @route decorator because i need other bottle functions like template , hook etc...

i've tried using it and it's ok but other bottle function seems not working

**Comment by dorel14** [comment]
For informations , i went back to 0.18.0 and it's now ok with my bottle functions

**Comment by DandyDev** [comment]
I'm curious what would happen if you upgrade to 0.18.1 or 0.18.2. Could you test? That way, I can pinpoint exactly where the bugs are introduced.

**Comment by dorel14** [comment]
Ok , il try and come back

**Comment by dorel14** [comment]
So , i've tried with 
0.18.1 => OK
0.18.2 => Broken , i get a 404 not found 
i've seen a fix in bottle import in your code so tried to import just like you 
`from machine.vendor import bottle`

in all my files needing import bottle and now  it's ok

**Comment by DandyDev** [comment]
Ah, I understand now. The error  you encountered is because I removed Bottle as external dependency and included the Bottle source code in Slack Machine itself. This is because I had to fix a bug in Bottle that wasn't fixed in the original package.

Glad you got it working again.
