### ISSUE TITLE
Error slack.rtm.client client.py:_dispatch_event

### ISSUE THREAD

**Issue by thosieucoi** [DandyDev/slack-machine#308]
@DandyDev  I got the error in 0.19.x version

`[ERROR] slack.rtm.client client.py:_dispatch_event:445 | When calling '#handle_message()' in the 'machine.dispatch' module the following error was raised: 'DU6G9SQBC'`

Would you please help me check this? It worked fine on 0.18.2 version

**Comment by dorel14** [comment]
Hi same for me when i try to @respond_to in a private channel. If i try to execute same function not in a private channel everything went ok

**Comment by unl1k3ly** [comment]
I'm getting the same error :/

**Comment by DandyDev** [comment]
This is fixed in 1db9ec84f14830bfbe226294b75abff1bf7bb018

**Comment by DandyDev** [comment]
You can upgrade to [v0.20](https://pypi.org/project/slack-machine/0.20.0/) to get the fixes
