### ISSUE TITLE
Using slack-machine in code

### ISSUE THREAD

**Issue by Tahvok** [DandyDev/slack-machine#31]
I would like to use slack-machine in code. Not by running slack-machine command.

I need to run the slack bot as a thread of a bigger application. I'm having a hard time finding a way to do this.

If it's already supported, please document it.

**Comment by DandyDev** [comment]
It is supported. You can run the bot from code like this:

```
from machine import Machine

bot = Machine()
bot.run()
```

You should be able to do this in a separate thread. Using multiprocessing instead of threading is probably better though.

Does this help?

**Comment by DandyDev** [comment]
One other remark: when instantiating Slack Machine like this, you can optionally provide a dict with settings (like `SLACK_API_TOKEN` etc.) If you don't, Slack Machine will try to find a `local_settings.py` module and try to import that.

**Comment by Tahvok** [comment]
Thanks! That works.
I've been using the 'main' method, but now I use the run method directly as you said.

What I'm trying to achieve, is a rest api access to the bot. For example, a third party application that wants to send a message via the bot, will send a request to the bot, and the bot will send a message to slack.

**Comment by DandyDev** [comment]
Glad it works for you! A couple of remarks:
- I'm planning to add an optional webserver to Slack Machine, that would allow you to expose routes so external applications can call your bot. That feature is mostly meant for callbacks in case you want to use Slack Buttons for instance, but it works for your case as well.
- It might be even easier for you, to just use [Slack Webhooks](https://api.slack.com/incoming-webhooks) for what you want. You can use webhooks to have applications send messages to Slack. Then you wouldn't need Slack Machine at all. Or you could use the [Slack WebApi](https://api.slack.com/web)

I'm glad Slack Machine is of use to you, but I'm wondering what Slack Machine adds for your use-case, that you can't achieve more directly with either the Slack WebApi or Slack Webhooks :)

**Comment by Tahvok** [comment]
The rest api is just additional feature I need in the bot. I still do need a fully featured framework, instead of using the slack webapi directly. Your framework just supports the most slack features I saw from all the frameworks I've checked, so I chose it. Just the api is what I'm missing.

I did work around it currently, by calling SlackClient directly from flask server, and I still have the bot running in a thread. So it would be pretty easy for us to move to your api implementation once available (I hope it will be soon), and remove the need for threading completely.

**Comment by DandyDev** [comment]
Great! Glad you like it.
I will keep this issue open, so I can notify you once the webserver part has been built :)

**Comment by DandyDev** [comment]
Update: I have created an initial webserver integration. It's based on [Bottle](https://bottlepy.org/docs/0.12/), because that's a nice light-weight framework. I've added a `@route` decorator to the `machine.plugins.decorators` package, that takes the same parameters as the Bottle `@route` decorator. You should use it on functions inside a `MachinePlugin` It will then automatically register the decorated function as a Bottle route, while also allowing you to use all the features of the Slack Machine Plugin API inside your route functions.

Slack Machine will take care of starting the webserver for you.

I haven't cut an official release yet with this feature, because it's not very thoroughly tested and documented yet. In the meanwhile you can already use it by cloning this repo and running `python setup.py install`.

Let me know if you run into any issues!

**Comment by Tahvok** [comment]
Thanks a lot!
Can you add other decorators as well? Like @get @post @put and the others?

**Comment by DandyDev** [comment]
You can provide any method to the `@route` decorator using the `method` parameter. Like so:

```python
@route("/hello/<name>", method="POST")
def my_exposed_function(self, name="World"):
    self.say('my-channel', '{} is talking to me'.format(name))
    return {"hello": name}

@route("/status", method=["POST", "GET"])
def my_other_function(self):
    return {"status": "I'm a-okay!"}
```

To be honest, I'd rather keep the API as simple as possible and not introduce too many decorators.

**Comment by DandyDev** [comment]
I guess this works now @Tahvok, so I'm closing the issue.
