### ISSUE TITLE
Running the default from the tutorial doesn't work

### ISSUE THREAD

**Issue by drdarina** [DandyDev/slack-machine#415]
Hi, I'm completely new to this and probably making some silly mistake. I've followed your tutorial so far but it's silently failing. My `local_settings.py` looks like this:

```
import os

SLACK_API_TOKEN = os.environ.get('SLACK_BOT_TOKEN')

PLUGINS = ['machine.plugins.builtin.general.HelloPlugin',
           'machine.plugins.builtin.general.PingPongPlugin',
           'plugins.hitchhikers.UltimateQuestionPlugin']
```

The slack bot token is correct, the bot exists and I can make it say things directly using the `slack_sdk` `WebClient`. When I run `slack-machine` I don't see any errors, but the bot is doing nothing. It just sits there. Posting `42`, `!42`, `@botname 42` etc all does nothing. No output on the console either. I tried setting log level to debug - still nothing and no new output in the console. Deleting the token from env variables worked as expected with `slack-machine` throwing an error at startup.

Why is this happening? Am I missing some step?

```
(slack-glossary) ➜  slack-glossary git:(master) ✗ slack-machine
Initializing Slack Machine:
    Loading settings...
    Initializing storage using backend: machine.storage.backends.memory.MemoryStorage
    Loading plugins...
        ✓ machine.plugins.builtin.general:HelloPlugin
        ✓ machine.plugins.builtin.general:PingPongPlugin
        ✓ plugins.hitchhikers:UltimateQuestionPlugin

Starting Slack Machine:
    ✓ Connected to Slack
    ✓ Scheduler started
Bottle v0.13-dev server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
    ✓ Web server started
    ✓ Dispatcher started
Hit Ctrl-C to quit.
```

I've also experimented with using pipenv instead of venv and installing requirements.txt first before installing slack-machine from pip. What I realise now I didn't try yet is installing slack-machine from github.

**Comment by drdarina** [comment]
This was completely my bad, I had created a slack app instead of a slack bot, despite what the tutorial says.

**Comment by AsheKR** [comment]
I was making the same mistake....
