### ISSUE TITLE
Issue with slackclient 2.7.3

### ISSUE THREAD

**Issue by stvnksslr** [DandyDev/slack-machine#434]
Still sorting out exactly what the heck is going on here and will submit a PR when I do if needed but it appears slack has done something to deprecate aiohttp < 3.6 connections

https://github.com/slackapi/python-slack-sdk/issues/912

popped up a few hours ago but wanted to throw this here to save anyone else time trying to debug.

EDIT: appears you can fix it by upgrading `aiohttp = "3.7.3"`

*note*: this does not appear to be a slack-machine issue itself but will effect users of it none the less

**Comment by cchadowitz-pf** [comment]
I'm using slack-machine in docker, based on the docker image `python:3-slim`. Once I pulled the latest of that docker image and updated my local slack-machine build to the latest (which includes `slackclient==2.9.3` from the `requirements.txt`), it pulled in `aiohttp` 3.7.3.

With all of that, it's back up and running for me. Thanks for opening this - helped me track it down!

**Comment by dorel14** [comment]
Hi 
Same for me but running aiohttp - pip install -U aiohttp makes the job and it's now running

**Comment by stvnksslr** [comment]
This seems to be fixed upstream now, going to close.
