### ISSUE TITLE
Slack api im.open method has been removed 

### ISSUE THREAD

**Issue by enver** [DandyDev/slack-machine#440]
Currently, `reply_dm` method does not work.
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api.

@DandyDev Could you please create a hotfix branch for 0.18.2 version, I'd like to submit PR against this version and master.

**Comment by cchadowitz-pf** [comment]
I've had a fix for that outstanding for a little while in PR #401 FYI (as well as a minor bugfix for something else). Not sure if there's something holding it up from being merged but either way :)

**Comment by enver** [comment]
@cchadowitz-pf I totally missed that one, tnx.
@DandyDev I'd still like to submit patch against 0.18.2 and we can continue with #401 for main branch.

**Comment by dorel14** [comment]
hello can you publish a version with the hotfix some of my plugins are down

thx

**Comment by DandyDev** [comment]
I will have a look this weekend. Sorry for the delays. Just got a new job and a new puppy that needs care :)

**Comment by cchadowitz-pf** [comment]
FYI #401 has been merged and I believe a new release cut (v0.21.0).
