### ISSUE TITLE
Move to python-slack-sdk

### ISSUE THREAD

**Issue by DandyDev** [DandyDev/slack-machine#443]
Currently, slack-machine still uses the old `slackclient` library. That has been superseded by [python-slack-sdk](https://github.com/slackapi/python-slack-sdk). We should move to using that library.

**Comment by Berjiz** [comment]
I read through the migration [page](https://slack.dev/python-slack-sdk/v3-migration/)

Regarding the last two points in their guide about run_async and aiohttp. Slack machine doesn't use these parts so is unaffected, correct?

**Comment by DandyDev** [comment]
Correct. Although I want to look into using the async version at some point, for now it's a matter of changing the dependency and the import paths.
