### ISSUE TITLE
More flexible python requirements?

### ISSUE THREAD

**Issue by Faqa** [DandyDev/slack-machine#493]
Hi,

Is there any chance a future version of this package could get a less constrained set of requirements? I'm trying to fit it into a larger context with a lot of different requirements. Even just pinning to a specific minor would help.

**Comment by DandyDev** [comment]
Hey @Faqa I've been a bit inactive of late and saw your message only now. Could you tell me in what ways you want the requirements to be less constrained, and what requirements you're referring to?
