### ISSUE TITLE
feature request: extend redis backend

### ISSUE THREAD

**Issue by cabrinha** [DandyDev/slack-machine#63]
Let's extend the redis backend to support more actions like:

* https://redis.io/commands/scan
* https://redis.io/commands/hkeys
* https://redis.io/commands/keys

This would be in order to scan or get all keys for a given plugin and iterate over them.

I'm trying to create a "Karma" plugin and I'd like to show the top Karma scores:

```python
from machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import listen_to, respond_to
import re


class Karma(MachineBasePlugin):
    @respond_to(r'(?P<user>.*) \+\+')
    def up(self, msg, user):
        if self.storage.has(user):
            karma = self.storage.get(user)
            karma += 1
            self.storage.set(user, karma)
            msg.say('{}\'s karma is now: {}'.format(user, karma))
        else:
            self.storage.set(user, 1)
            msg.say('No karma found for: {}, setting to 1'.format(user))

    @respond_to(r'(?P<user>.*) \-\-')
    def down(self, msg, user):
        if self.storage.has(user):
            karma = self.storage.get(user)
            karma -= 1
            self.storage.set(user, karma)
            msg.say('{}\'s karma is now: {}'.format(user, karma))
        else:
            self.storage.set(user, -1)
            msg.say('No karma found for: {}, setting to -1'.format(user))

    @respond_to(r'.*(top karma).*')
    def top(self, msg):
        for i in self.storage.keys(pattern='*'):
            print(i)
```

in `machine/storage/backends/redis.py`:

```python
...
    def get(self, key):
        return self._redis.get(self._prefix(key))

    def keys(self, pattern):
        return self._redis.keys(pattern='*')
...
```

Something like this...

But, I get: `AttributeError: 'PluginStorage' object has no attribute 'keys'`

**Comment by DandyDev** [comment]
Great idea! I'll have to think a bit on it, but I'll get back to you on this!

**Comment by internaught** [comment]
I'm adding the following right underneath http://slack-machine.readthedocs.io/en/latest/_modules/machine/storage.html#PluginStorage.get:

```python
    def keys(self, key, shared=False):
        """Retrieve data by key

        :param key: key for the data to retrieve
        :param shared: ``True/False`` wether to retrieve data from the shared (global) namespace.
        :return: the data, or ``None`` if the key cannot be found/has expired
        """
        namespaced_key = self._namespace_key(key, shared)
        value = Storage.get_instance().keys(namespaced_key)
        if value:
            return dill.loads(value)
        else:
            return None
```
But, I'm still getting the error: `AttributeError: 'PluginStorage' object has no attribute 'keys'`.

Is there something else I'm missing?

**Comment by internaught** [comment]
Update: pretty sure im getting the hang of extending this module: https://github.com/internaught/slack-machine/commit/274e97f47e20388b701ad2e7ce7f546a7201d04e

I got my karma implementation working, added the scan_iter function to the redis backend and created some new Slack Web API calls.

How can I get these contributions back into slack-machine?
